%YAML 1.2
---
_name: Run
run_duration:
  description: Simulation run time
  value:
    type: int
    default: 3600
    range:
      min: 1
      max: 3153600000
    units: s
dt:
  description: Model time step
  value:
    type: float
    default: 600.0
    range:
      min: 1.0
      max: 31536000.0
    units: s
rti_file:
  description: RiverTools info file
  value:
    type: file
    default: default.rti
    files:
    - default.rti
pixel_file:
  description: Monitored pixel/grid file
  value:
    type: file
    default: 'off'
    files:
    - 'off'

---
_name: Input
code_file:
  description: RiverTools grid file of D8 flow codes
  value:
    type: file
    default: default_flow.rtg
    files:
    - default_flow.rtg
slope_file:
  description: RiverTools grid file of D8 slopes
  value:
    type: file
    default: default_slope.rtg
    files:
    - default_slope.rtg
roughness_option:
  description: Roughness option
  value:
    type: choice
    default: Manning's formula
    choices:
    - Manning's formula
    - Law of the wall
roughness_type:
  description: Roughness value (Manning's <em>n</em> or roughness length <em>z<sub>0</sub></em>)
  group:
    name: roughness_group
    leader: true
    members: 2
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m-(1/3) s or m
roughness_scalar:
  description: Scalar value
  group:
    name: roughness_group
  value:
    type: float
    default: 0.1
    range:
      min: 0.0
      max: 5.0
roughness_file:
  description: Grid, time series, or grid sequence file
  group:
    name: roughness_group
  value:
    type: file
    default: 'off'
    files:
    - 'off'
width_type:
  description: Bed width of trapezoid cross-section
  group:
    name: width_group
    leader: true
    members: 2
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m
width_scalar:
  description: Scalar value
  group:
    name: width_group
  value:
    type: float
    default: 10.0
    range:
      min: 0.0
      max: 1E4
width_file:
  description: Grid, time series, or grid sequence file
  group:
    name: width_group
  value:
    type: file
    default: 'off'
    files:
    - 'off'
angle_type:
  description: Bank angle of trapezoid cross-section
  group:
    name: angle_group
    leader: true
    members: 2
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: deg
angle_scalar:
  description: Scalar value
  group:
    name: angle_group
  value:
    type: float
    default: 1.0
    range:
      min: 0.0
      max: 360.0
angle_file:
  description: Grid, time series, or grid sequence file
  group:
    name: angle_group
  value:
    type: file
    default: 'off'
    files:
    - 'off'
d0_type:
  description: Initial flow depth
  group:
    name: d0_group
    leader: true
    members: 2
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m
d0_scalar:
  description: Scalar value
  group:
    name: d0_group
  value:
    type: float
    default: 0.0
    range:
      min: 0.0
      max: 0.0
d0_file:
  description: Grid, time series, or grid sequence file
  group:
    name: d0_group
  value:
    type: file
    default: 'off'
    files:
    - 'off'
sinu_type:
  description: Absolute channel sinuosity
  group:
    name: sinu_group
    leader: true
    members: 2
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m m-1
sinu_scalar:
  description: Scalar value
  group:
    name: sinu_group
  value:
    type: float
    default: 1.0
    range:
      min: 0.0
      max: 3.0
sinu_file:
  description: Grid, time series, or grid sequence file
  group:
    name: sinu_group
  value:
    type: file
    default: 'off'
    files:
    - 'off'

