%YAML 1.2
---
_name: Run
run_duration:
  description: Simulation run time
  value:
    type: int
    default: 10000
    range:
      min: 1
      max: 3153600000
    units: s
dt:
  description: Model time step
  value:
    type: float
    default: 6.0
    range:
      min: 1
      max: 31536000.0
    units: s
n_steps:
  description: Model number of steps
  value:
    type: int
    default: 5000
    range:
      min: 1
      max: 31536000
    units: '-'
rti_file:
  description: RiverTools info file
  value:
    type: file
    default: default.rti
    files:
    - default.rti
stop_method:
  description: Stopping method
  value:
    type: choice
    default: Q_peak_fraction
    choices:
    - Q_peak_fraction
    - Until_model_time
    - Until_n_steps
    units: '-'
Qp_fraction:
  description: Value for q_peak_fraction method
  value:
    type: Float
    default: '0.05'
    range:
      min: '0.0'
      max: '1.0'
    units: '-'
T_stop_model:
  description: Value for until_model_time method
  value:
    type: Float
    default: '2000'
    range:
      min: '0.0'
      max: 1e9
    units: min

